In [53]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [54]:
df = pd.read_csv('Bengaluru_House_Data.csv')

In [55]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [56]:
df.shape

(13320, 9)

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [58]:
df['society'].isnull().sum()

np.int64(5502)

In [59]:
df.duplicated().sum()

np.int64(529)

In [60]:
for column in df.columns:
    print(df[column].value_counts())
    print("*"*20)

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
********************
availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
15-Aug               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
********************
location
Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: count, Length: 1305, dtype: int64
********************
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: count, dtype: int64
********************
society
GrrvaGr    80
PrarePa    76
Sryalan    59
Prtates    59
GMown E    56
           ..
Amionce     1
JaghtDe     1
Jauraht     1
Brity U     1
RSntsAp     1
Name: count, Length: 2688, dtype: int64
********************
total_sqft
1200    843
1100    221
1500    205
2400    196
600     180
       ...
3580      1
2461      1
1437      1
2155      1
4689      1
Name: count, Length: 2117, dtype: int64
********************
bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
13.0       3
11.0       3
16.0       2
27.0       1
40.0       1
15.0       1
14.0       1
18.0       1
Name: count, dtype: int64
********************
balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64
********************
price
75.00     310
65.00     302
55.00     275
60.00     270
45.00     240
         ...
351.00      1
54.10       1
80.64       1
32.73       1
488.00      1
Name: count, Length: 1994, dtype: int64
********************

In [61]:
df.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [62]:
df.drop(columns= ['area_type' , 'availability' , 'society' , 'balcony'] , inplace =True)

In [63]:
df.head()

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [64]:
df.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [66]:
df['location'].value_counts()

location
Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: count, Length: 1305, dtype: int64

In [67]:
df['location'] = df['location'].fillna('Sarjapur  Road')

In [68]:
df['location'].value_counts()

location
Whitefield                        540
Sarjapur  Road                    400
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: count, Length: 1305, dtype: int64

In [69]:
df['size'].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [70]:
df['sizesize'] = df['size'].fillna('2 BHK')

In [71]:
df.head()

                   location       size total_sqft  bath   price   sizesize
0  Electronic City Phase II      2 BHK       1056   2.0   39.07      2 BHK
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00  4 Bedroom
2               Uttarahalli      3 BHK       1440   2.0   62.00      3 BHK
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00      3 BHK
4                  Kothanur      2 BHK       1200   2.0   51.00      2 BHK

In [72]:
bath_mean = df['bath'].mean()

In [73]:
bath_mean

np.float64(2.6926096474673513)

In [74]:
df['bath'] = df['bath'].fillna(bath_mean)

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13320 non-null  float64
 4   price       13320 non-null  float64
 5   sizesize    13320 non-null  object
dtypes: float64(2), object(4)
memory usage: 624.5+ KB

In [76]:
df['bhk'] = df['size'] = df['size'].str.split().str.get(0).astype('Int64')

In [77]:
df[df.bhk > 20]

                       location  size total_sqft  bath  price    sizesize  bhk
1718  2Electronic City Phase II    27       8000  27.0  230.0      27 BHK   27
4684                Munnekollal    43       2400  40.0  660.0  43 Bedroom   43

In [78]:
df['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      shape=(2117,), dtype=object)

In [79]:
def convertRange(x):
    temp = x.split('_')
    if len(temp) == 2:
        return (float(temp[0]) + float(temp[1]))/2
    try:
        return float(x)
    except:
        return None

In [80]:
df['total_sqft'] = df['total_sqft'].apply(convertRange)

In [81]:
df.head()

                   location  size  total_sqft  bath   price   sizesize  bhk
0  Electronic City Phase II     2      1056.0   2.0   39.07      2 BHK    2
1          Chikka Tirupathi     4      2600.0   5.0  120.00  4 Bedroom    4
2               Uttarahalli     3      1440.0   2.0   62.00      3 BHK    3
3        Lingadheeranahalli     3      1521.0   3.0   95.00      3 BHK    3
4                  Kothanur     2      1200.0   2.0   51.00      2 BHK    2

# price_per_sqaure_feet

In [82]:
df['price_per_sqft'] = df['price']*100000 / df['total_sqft']

In [83]:
df['price_per_sqft']

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
13319     3090.909091
Name: price_per_sqft, Length: 13320, dtype: float64

In [84]:
df.describe()

,size,total_sqft,bath,price,bhk,price_per_sqft
count,13304.0,13073.000000,13320.000000,13320.000000,13304.0,1.307300e+04
mean,2.803743,1554.942029,2.692610,112.565627,2.803743,7.949600e+03
std,1.294974,1238.458773,1.337777,148.971674,1.294974,1.072440e+05
min,1.0,1.000000,1.000000,8.000000,1.0,2.678298e+02
25%,2.0,1100.000000,2.000000,50.000000,2.0,4.265734e+03
50%,3.0,1275.000000,2.000000,72.000000,3.0,5.454545e+03
75%,3.0,1670.000000,3.000000,120.000000,3.0,7.338057e+03
max,43.0,52272.000000,40.000000,3600.000000,43.0,1.200000e+07

In [85]:
df['location'].value_counts()

location
Whitefield                        540
Sarjapur  Road                    400
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: count, Length: 1305, dtype: int64

In [86]:
df['location']= df['location'].apply(lambda x: x.strip())
location_counts = df['location'].value_counts()

In [87]:
location_counts_less_10 = location_counts[location_counts <=10]
location_counts_less_10

location
Dairy Circle                      10
Nagappa Reddy Layout              10
Basapura                          10
1st Block Koramangala             10
Sector 1 HSR Layout               10
                                  ..
Bapuji Layout                      1
1st Stage Radha Krishna Layout     1
BEML Layout 5th stage              1
singapura paradise                 1
Abshot Layout                      1
Name: count, Length: 1053, dtype: int64

In [88]:
df['location'] = df['location'].apply(lambda x: 'other' if x in location_counts_less_10 else x )

In [89]:
df['location'].value_counts()

location
other                 2885
Whitefield             541
Sarjapur  Road         400
Electronic City        304
Kanakpura Road         273
                      ...
Nehru Nagar             11
Banjara Layout          11
LB Shastri Nagar        11
Pattandur Agrahara      11
Narayanapura            11
Name: count, Length: 242, dtype: int64

# outliers detection and remove

In [90]:
df.describe()

,size,total_sqft,bath,price,bhk,price_per_sqft
count,13304.0,13073.000000,13320.000000,13320.000000,13304.0,1.307300e+04
mean,2.803743,1554.942029,2.692610,112.565627,2.803743,7.949600e+03
std,1.294974,1238.458773,1.337777,148.971674,1.294974,1.072440e+05
min,1.0,1.000000,1.000000,8.000000,1.0,2.678298e+02
25%,2.0,1100.000000,2.000000,50.000000,2.0,4.265734e+03
50%,3.0,1275.000000,2.000000,72.000000,3.0,5.454545e+03
75%,3.0,1670.000000,3.000000,120.000000,3.0,7.338057e+03
max,43.0,52272.000000,40.000000,3600.000000,43.0,1.200000e+07

In [91]:
(df['total_sqft'] / df['bhk']).describe()

count       13065.0
mean     572.932308
std      389.541137
min            0.25
25%           472.0
50%           551.0
75%           625.0
max         26136.0
dtype: Float64

In [92]:
data = df[((df ['total_sqft']/df['bhk']) >= 300)]
data.describe()

,size,total_sqft,bath,price,bhk,price_per_sqft
count,12321.0,12321.000000,12321.000000,12321.000000,12321.0,12321.000000
mean,2.651895,1589.770648,2.562255,111.428270,2.651895,6323.355553
std,0.973929,1261.816721,1.072713,152.743702,0.973929,4185.986202
min,1.0,300.000000,1.000000,9.000000,1.0,267.829813
25%,2.0,1117.000000,2.000000,49.360000,2.0,4209.541628
50%,3.0,1300.000000,2.000000,70.000000,3.0,5300.000000
75%,3.0,1700.000000,3.000000,115.000000,3.0,6938.483548
max,16.0,52272.000000,16.000000,3600.000000,16.0,176470.588235

In [93]:
data.shape

(12321, 8)

In [94]:
data.price_per_sqft.describe()

count     12321.000000
mean       6323.355553
std        4185.986202
min         267.829813
25%        4209.541628
50%        5300.000000
75%        6938.483548
max      176470.588235
Name: price_per_sqft, dtype: float64

In [95]:
# Function from the video (1 Standard Deviation filter per location)
def remove_outliers_sqft(df):
    df_output = pd.DataFrame()
    for key, subdf in df.groupby('location'):
        m = np.mean(subdf.price_per_sqft)
        st = np.std(subdf.price_per_sqft)
        gen_df = subdf[(subdf.price_per_sqft > (m - st)) & (subdf.price_per_sqft <= (m + st))]
        df_output = pd.concat([df_output, gen_df], ignore_index=True)
    return df_output
data.describe()

,size,total_sqft,bath,price,bhk,price_per_sqft
count,12321.0,12321.000000,12321.000000,12321.000000,12321.0,12321.000000
mean,2.651895,1589.770648,2.562255,111.428270,2.651895,6323.355553
std,0.973929,1261.816721,1.072713,152.743702,0.973929,4185.986202
min,1.0,300.000000,1.000000,9.000000,1.0,267.829813
25%,2.0,1117.000000,2.000000,49.360000,2.0,4209.541628
50%,3.0,1300.000000,2.000000,70.000000,3.0,5300.000000
75%,3.0,1700.000000,3.000000,115.000000,3.0,6938.483548
max,16.0,52272.000000,16.000000,3600.000000,16.0,176470.588235

In [96]:
def remove_outliers_iqr(df):
    df_output = pd.DataFrame()
    for key, subdf in df.groupby('location'):
        q1 = subdf.price_per_sqft.quantile(0.25)
        q3 = subdf.price_per_sqft.quantile(0.75)
        iqr = q3 - q1
        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr
        gen_df = subdf[(subdf.price_per_sqft >= lower_bound) & (subdf.price_per_sqft <= upper_bound)]
        df_output = pd.concat([df_output, gen_df], ignore_index=True)
    return df_output
data.describe()

,size,total_sqft,bath,price,bhk,price_per_sqft
count,12321.0,12321.000000,12321.000000,12321.000000,12321.0,12321.000000
mean,2.651895,1589.770648,2.562255,111.428270,2.651895,6323.355553
std,0.973929,1261.816721,1.072713,152.743702,0.973929,4185.986202
min,1.0,300.000000,1.000000,9.000000,1.0,267.829813
25%,2.0,1117.000000,2.000000,49.360000,2.0,4209.541628
50%,3.0,1300.000000,2.000000,70.000000,3.0,5300.000000
75%,3.0,1700.000000,3.000000,115.000000,3.0,6938.483548
max,16.0,52272.000000,16.000000,3600.000000,16.0,176470.588235

In [97]:
def bhk_outlier_remover(df):
    exclude_indices = np.array([])
    for location, location_df in df.groupby('location'):
        bhk_stats = {}
        for bhk, bhk_df in location_df.groupby('bhk'):
            bhk_stats[bhk] = {
                'mean': np.mean(bhk_df.price_per_sqft),
                'std': np.std(bhk_df.price_per_sqft),
                'count': bhk_df.shape[0]
            }
        for bhk, bhk_df in location_df.groupby('bhk'):
            stats = bhk_stats.get(bhk - 1)
            if stats and stats['count'] > 5:
                exclude_indices = np.append(
                    exclude_indices, 
                    bhk_df[bhk_df.price_per_sqft < (stats['mean'])].index.values
                )
    return df.drop(exclude_indices, axis='index')

# Applying the function
data = bhk_outlier_remover(data)

In [98]:
data

,location,size,total_sqft,bath,price,sizesize,bhk,price_per_sqft
0,Electronic City Phase II,2,1056.0,2.0,39.07,2 BHK,2,3699.810606
2,Uttarahalli,3,1440.0,2.0,62.00,3 BHK,3,4305.555556
3,Lingadheeranahalli,3,1521.0,3.0,95.00,3 BHK,3,6245.890861
4,Kothanur,2,1200.0,2.0,51.00,2 BHK,2,4250.000000
6,Old Airport Road,4,2732.0,4.0,204.00,4 BHK,4,7467.057101
...,...,...,...,...,...,...,...,...
13314,Green Glen Layout,3,1715.0,3.0,112.00,3 BHK,3,6530.612245
13316,other,4,3600.0,5.0,400.00,4 BHK,4,11111.111111
13317,Raja Rajeshwari Nagar,2,1141.0,2.0,60.00,2 BHK,2,5258.545136
13318,Padmanabhanagar,4,4689.0,4.0,488.00,4 BHK,4,10407.336319
13319,Doddathoguru,1,550.0,1.0,17.00,1 BHK,1,3090.909091

In [99]:
data.shape

(8572, 8)

In [100]:
data.head()

,location,size,total_sqft,bath,price,sizesize,bhk,price_per_sqft
0,Electronic City Phase II,2,1056.0,2.0,39.07,2 BHK,2,3699.810606
2,Uttarahalli,3,1440.0,2.0,62.00,3 BHK,3,4305.555556
3,Lingadheeranahalli,3,1521.0,3.0,95.00,3 BHK,3,6245.890861
4,Kothanur,2,1200.0,2.0,51.00,2 BHK,2,4250.000000
6,Old Airport Road,4,2732.0,4.0,204.00,4 BHK,4,7467.057101

In [101]:
df

,location,size,total_sqft,bath,price,sizesize,bhk,price_per_sqft
0,Electronic City Phase II,2,1056.0,2.0,39.07,2 BHK,2,3699.810606
1,Chikka Tirupathi,4,2600.0,5.0,120.00,4 Bedroom,4,4615.384615
2,Uttarahalli,3,1440.0,2.0,62.00,3 BHK,3,4305.555556
3,Lingadheeranahalli,3,1521.0,3.0,95.00,3 BHK,3,6245.890861
4,Kothanur,2,1200.0,2.0,51.00,2 BHK,2,4250.000000
...,...,...,...,...,...,...,...,...
13315,Whitefield,5,3453.0,4.0,231.00,5 Bedroom,5,6689.834926
13316,other,4,3600.0,5.0,400.00,4 BHK,4,11111.111111
13317,Raja Rajeshwari Nagar,2,1141.0,2.0,60.00,2 BHK,2,5258.545136
13318,Padmanabhanagar,4,4689.0,4.0,488.00,4 BHK,4,10407.336319
13319,Doddathoguru,1,550.0,1.0,17.00,1 BHK,1,3090.909091

In [102]:
df.drop(columns=['sizesize' , 'price_per_sqft'] , inplace = True)

In [109]:
df.head()

                   location  size  total_sqft  bath   price  bhk
0  Electronic City Phase II     2      1056.0   2.0   39.07    2
1          Chikka Tirupathi     4      2600.0   5.0  120.00    4
2               Uttarahalli     3      1440.0   2.0   62.00    3
3        Lingadheeranahalli     3      1521.0   3.0   95.00    3
4                  Kothanur     2      1200.0   2.0   51.00    2

<!-- testing code -->

In [115]:
df_encode = df

In [116]:
from sklearn.preprocessing import StandardScaler
numerical_cols = ['size' , 'total_sqft' , 'bath' , 'bhk']
scaler = StandardScaler()
df_encode[numerical_cols] = scaler.fit_transform(df_encode[numerical_cols])
df_encode.head()

                   location      size  total_sqft      bath   price       bhk
0  Electronic City Phase II -0.620687   -0.402889 -0.517751   39.07 -0.620687
1          Chikka Tirupathi  0.923804    0.843870  1.724859  120.00  0.923804
2               Uttarahalli  0.151558   -0.092814 -0.517751   62.00  0.151558
3        Lingadheeranahalli  0.151558   -0.027408  0.229786   95.00  0.151558
4                  Kothanur -0.620687   -0.286611 -0.517751   51.00 -0.620687

# ML

In [117]:
X = df_encode.drop(columns = ['price'])
y = df_encode['price']

In [118]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [119]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [120]:
print(X_train.shape)
print(X_test.shape)

(10656, 5)
(2664, 5)

In [ ]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled =  scaler.fit_transform(X_test)

In [121]:
models = {
    "Logistic Regration" : LogisticRegression(),
    "KNN" :KNeighborsClassifier(),
    "Naive Bayes" :GaussianNB(),
    "Decision Tree" :DecisionTreeClassifier(),
    "SVM" :SVC(probability =True)
}

NameError: name 'LogisticRegression' is not defined

In [ ]:
results =[]

In [ ]:
for name , model in models.items():
    model.fit(X_train_scaled , y_train)
    y_pred = model.predict(X_test_scaled)
    acc  = accuracy_score(y_test , y_pred)
    f1 = f1_score(y_test , y_pred)

    results.append({
        'model':name,
        'accuracy' :round(acc, 4),
        'F1 score': round(f1 ,4 )
    })